import { Pool, PoolClient } from "pg";
import { Redis } from "ioredis";  // named import: the default export is a namespace under ESM + node16 resolution

/**
 * The one place a message is created. Both the WebSocket handler and the REST
 * fallback route call this -- if sending ever forks into two implementations,
 * they will drift and one of them will be the buggy one.
 */

export interface SendMessageInput {
  conversationId: string;
  senderId: string;
  /** Generated by the client BEFORE the send goes out. Makes retries safe,
   *  and for a server-generated "system" message (call-service.ts) it's
   *  just a fresh random id -- there's no client retry to correlate. */
  clientMessageId: string;
  type: "text" | "image" | "file" | "system";
  content: string | null;
  replyToMessageId?: string | null;
  attachments?: Array<{ storageKey: string; fileType: string; sizeBytes: number }>;
}

export interface PersistedMessage {
  id: string;
  conversationId: string;
  senderId: string;
  seq: string; // bigint comes back as a string from node-pg; keep it a string
  type: string;
  content: string | null;
  replyToMessageId: string | null;
  createdAt: string;
  clientMessageId: string;
  /** True when this call matched an earlier send and nothing new was written. */
  deduplicated: boolean;
}

export class SendError extends Error {
  constructor(public code: string, message: string) {
    super(message);
  }
}

const MAX_CONTENT_LENGTH = 4000;
const PARTICIPANTS_TTL_SECONDS = 300;

// ---------------------------------------------------------------------------
// Authorisation
//
// Every send re-checks membership. Do not trust the socket's room membership
// for this: rooms are joined at connect time and a user removed from a group
// mid-session still holds the room until the server gets around to evicting
// them. The database (or its cache) is the authority.
// ---------------------------------------------------------------------------

export async function getParticipantIds(
  pool: Pool,
  redis: Redis,
  conversationId: string
): Promise<string[]> {
  const key = `conv:${conversationId}:participants`;
  const cached = await redis.smembers(key);
  if (cached.length > 0) return cached;

  const { rows } = await pool.query<{ user_id: string }>(
    `SELECT user_id FROM conversation_participants WHERE conversation_id = $1`,
    [conversationId]
  );
  if (rows.length === 0) return [];

  const ids = rows.map((r) => r.user_id);
  await redis
    .multi()
    .sadd(key, ...ids)
    .expire(key, PARTICIPANTS_TTL_SECONDS)
    .exec();
  return ids;
}

/** Call this from every path that adds or removes a participant. */
export async function invalidateParticipants(redis: Redis, conversationId: string) {
  await redis.del(`conv:${conversationId}:participants`);
}

/** Shared by the socket handlers and the REST routes -- one authorization
 *  path, not two that can drift apart. */
export async function assertParticipant(
  pool: Pool,
  redis: Redis,
  conversationId: string,
  userId: string
): Promise<void> {
  const ids = await getParticipantIds(pool, redis, conversationId);
  if (!ids.includes(userId)) throw new SendError("NOT_A_PARTICIPANT", "Bukan bagian dari percakapan ini");
}

/** The Taruna re-join gate for this caller in this conversation, if any --
 *  see taruna.ts. Not cached like participant ids: it changes rarely and
 *  every history/backfill/sync call needs a fresh value, not a 5-minute-old
 *  one that could momentarily leak a still-pending backlog. */
export async function getPendingReleaseSeq(
  pool: Pool,
  conversationId: string,
  userId: string
): Promise<number | null> {
  const { rows } = await pool.query<{ pending_release_seq: number | null }>(
    `SELECT pending_release_seq FROM conversation_participants
      WHERE conversation_id = $1 AND user_id = $2`,
    [conversationId, userId]
  );
  return rows[0]?.pending_release_seq ?? null;
}

// ---------------------------------------------------------------------------
// The send path
// ---------------------------------------------------------------------------

export async function sendMessage(
  pool: Pool,
  redis: Redis,
  input: SendMessageInput
): Promise<PersistedMessage> {
  if (input.type === "text") {
    const body = (input.content ?? "").trim();
    if (body.length === 0) throw new SendError("EMPTY_MESSAGE", "Pesan tidak boleh kosong");
    if (body.length > MAX_CONTENT_LENGTH)
      throw new SendError("MESSAGE_TOO_LONG", `Maksimal ${MAX_CONTENT_LENGTH} karakter`);
    input.content = body;
  }

  const participants = await getParticipantIds(pool, redis, input.conversationId);
  if (!participants.includes(input.senderId))
    throw new SendError("NOT_A_PARTICIPANT", "Kamu bukan bagian dari percakapan ini");

  const client = await pool.connect();
  try {
    return await insertWithSeq(client, input);
  } catch (err: any) {
    // The client retried a send whose ack it never received. The row is
    // already there; return it and let the client reconcile as normal.
    if (err.code === "23505" && err.constraint === "messages_client_id_key") {
      await client.query("ROLLBACK").catch(() => {});
      const existing = await findByClientMessageId(
        client,
        input.conversationId,
        input.clientMessageId
      );
      if (existing) return { ...existing, deduplicated: true };
    }
    throw err;
  } finally {
    client.release();
  }
}

/**
 * Keep this transaction as short as physically possible.
 *
 * The UPDATE takes a row lock on the conversation, and every other sender in
 * the same conversation queues behind it. That serialisation is deliberate --
 * it is what makes seq gapless and what makes seq order equal commit order --
 * but it means anything slow in here (an S3 round trip, an SFU API call, a
 * fan-out) becomes head-of-line blocking for the whole conversation.
 * Attachments must already be uploaded and validated before this runs.
 */
async function insertWithSeq(
  client: PoolClient,
  input: SendMessageInput
): Promise<PersistedMessage> {
  await client.query("BEGIN");

  const { rows: seqRows } = await client.query<{ last_seq: string }>(
    `UPDATE conversations
        SET last_seq = last_seq + 1,
            last_message_at = now()
      WHERE id = $1
      RETURNING last_seq`,
    [input.conversationId]
  );
  if (seqRows.length === 0) {
    await client.query("ROLLBACK");
    throw new SendError("CONVERSATION_NOT_FOUND", "Percakapan tidak ditemukan");
  }
  const seq = seqRows[0].last_seq;

  // A reply must live in the same conversation, or you can quote a message out
  // of a conversation the reader cannot see.
  if (input.replyToMessageId) {
    const { rowCount } = await client.query(
      `SELECT 1 FROM messages WHERE id = $1 AND conversation_id = $2 AND deleted_at IS NULL`,
      [input.replyToMessageId, input.conversationId]
    );
    if (rowCount === 0) {
      await client.query("ROLLBACK");
      throw new SendError("REPLY_TARGET_INVALID", "Tidak bisa membalas pesan tersebut");
    }
  }

  const { rows } = await client.query(
    `INSERT INTO messages
       (conversation_id, sender_id, type, content, reply_to_message_id, seq, client_message_id)
     VALUES ($1, $2, $3, $4, $5, $6, $7)
     RETURNING id, conversation_id, sender_id, seq, type, content,
               reply_to_message_id, created_at, client_message_id`,
    [
      input.conversationId,
      input.senderId,
      input.type,
      input.content,
      input.replyToMessageId ?? null,
      seq,
      input.clientMessageId,
    ]
  );
  const row = rows[0];

  if (input.attachments?.length) {
    for (const a of input.attachments) {
      await client.query(
        `INSERT INTO attachments (message_id, storage_key, file_type, file_size_bytes)
         VALUES ($1, $2, $3, $4)`,
        [row.id, a.storageKey, a.fileType, a.sizeBytes]
      );
    }
  }

  // The sender has, by definition, read their own message.
  await client.query(
    `UPDATE conversation_participants
        SET last_read_seq = $3
      WHERE conversation_id = $1 AND user_id = $2 AND last_read_seq < $3`,
    [input.conversationId, input.senderId, seq]
  );

  await client.query("COMMIT");

  return {
    id: row.id,
    conversationId: row.conversation_id,
    senderId: row.sender_id,
    seq: row.seq,
    type: row.type,
    content: row.content,
    replyToMessageId: row.reply_to_message_id,
    createdAt: row.created_at.toISOString(),
    clientMessageId: row.client_message_id,
    deduplicated: false,
  };
}

async function findByClientMessageId(
  client: PoolClient,
  conversationId: string,
  clientMessageId: string
): Promise<PersistedMessage | null> {
  const { rows } = await client.query(
    `SELECT id, conversation_id, sender_id, seq, type, content,
            reply_to_message_id, created_at, client_message_id
       FROM messages
      WHERE conversation_id = $1 AND client_message_id = $2`,
    [conversationId, clientMessageId]
  );
  if (rows.length === 0) return null;
  const row = rows[0];
  return {
    id: row.id,
    conversationId: row.conversation_id,
    senderId: row.sender_id,
    seq: row.seq,
    type: row.type,
    content: row.content,
    replyToMessageId: row.reply_to_message_id,
    createdAt: row.created_at.toISOString(),
    clientMessageId: row.client_message_id,
    deduplicated: true,
  };
}

// ---------------------------------------------------------------------------
// Backfill
//
// Because seq is gapless and commit-ordered, "everything I missed" is a single
// keyset scan. This is also the recovery path if the process dies between
// COMMIT and fan-out: the message is durable, nobody got the push, and the
// next reconnect picks it up.
//
// The second clause covers edits and deletes. Those update a row in place and
// deliberately do NOT allocate a new seq -- otherwise the message would jump
// position in every timeline -- so the seq cursor alone cannot see them, and a
// client offline during an edit would show stale text indefinitely.
//
// A timestamp IS safe here, unlike for ordering, because mutations are applied
// as upserts keyed by message id: over-fetching costs nothing, so a generous
// overlap window fully absorbs the commit-visibility race.
// ---------------------------------------------------------------------------

export const BACKFILL_LIMIT = 200;

/** Overlap absorbed into the mutation cursor to cover the commit race. */
const MUTATION_OVERLAP_SECONDS = 60;

export async function backfill(
  pool: Pool,
  conversationId: string,
  afterSeq: string | number,
  /** Server-issued timestamp from the client's previous sync; null on first run. */
  mutatedSince: string | null,
  /** Taruna re-join gate (see taruna.ts / 005_account_kinds.sql). NULL for
   *  every caller today and for Ceko always -- purely additive, no-op
   *  unless a caller actually has a pending release point set. */
  pendingReleaseSeq: string | number | null = null
): Promise<{ messages: any[]; truncated: boolean; syncedAt: string }> {
  const { rows } = await pool.query(
    `SELECT id, conversation_id, sender_id, seq, type, content,
            reply_to_message_id, created_at, edited_at, deleted_at, mutated_at,
            client_message_id
       FROM messages
      WHERE conversation_id = $1
        AND (seq > $2
             OR ($3::timestamptz IS NOT NULL
                 AND mutated_at > $3::timestamptz - make_interval(secs => $4)))
        AND ($6::bigint IS NULL OR seq > $6::bigint)
      ORDER BY seq ASC
      LIMIT $5`,
    [conversationId, afterSeq, mutatedSince, MUTATION_OVERLAP_SECONDS, BACKFILL_LIMIT + 1, pendingReleaseSeq]
  );

  // The client echoes this back as its next mutation cursor. Server clock, not
  // theirs -- a device running fast would otherwise skip its own edits.
  const { rows: clock } = await pool.query<{ now: Date }>(`SELECT now() AS now`);

  const truncated = rows.length > BACKFILL_LIMIT;
  return {
    messages: rows.slice(0, BACKFILL_LIMIT),
    truncated,
    syncedAt: clock[0].now.toISOString(),
  };
}

/**
 * History pagination scrolls the other way: newest first, walking backwards.
 * Same index, same cursor type as backfill -- one ordering concept, not two.
 */
export async function history(
  pool: Pool,
  conversationId: string,
  beforeSeq: string | number | null,
  limit = 50,
  /** See backfill()'s parameter of the same name. */
  pendingReleaseSeq: string | number | null = null
) {
  const { rows } = await pool.query(
    `SELECT id, conversation_id, sender_id, seq, type, content,
            reply_to_message_id, created_at, edited_at, deleted_at
       FROM messages
      WHERE conversation_id = $1
        AND ($2::bigint IS NULL OR seq < $2::bigint)
        AND ($4::bigint IS NULL OR seq > $4::bigint)
      ORDER BY seq DESC
      LIMIT $3`,
    [conversationId, beforeSeq, Math.min(limit, 100), pendingReleaseSeq]
  );
  return rows.reverse();
}
